name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-cli:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
        - target: armv7-unknown-linux-gnueabihf
          os: ubuntu-latest
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: FranzDiebold/github-env-vars-action@v1.2.1
    - uses: dtolnay/rust-toolchain@nightly
      with:
        targets: ${{ matrix.target }}

    - name: Configure caching
      uses: actions/cache@v2
      # Caching disabled on macos due to https://github.com/actions/cache/issues/403
      if: ${{ matrix.os != 'macos-latest' }}
      with:
        key: ${{ matrix.os }}-${{ matrix.target }}
        path: |
          ${{ env.HOME }}/.cargo
          target


    - name: Build CLI
      run: |
        cross build --release  --target ${{ matrix.target }}

    - name: Copy / Rename utility
      run: |
        cp target/${{ matrix.target }}/release/mcp4xxx-util mcp4xxx-util-${{ matrix.target }}
        tar -czvf mcp4xxx-util-${{ matrix.target }}.tgz mcp4xxx-util-${{ matrix.target }}

    - name: Upload utility artifacts
      uses: actions/upload-artifact@v1
      with:
        name: mcp4xxx-util-${{ matrix.target }}
        path: mcp4xxx-util-${{ matrix.target }}

    - name: Upload utility binary to release
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mcp4xxx-util-${{ matrix.target }}.tgz
        asset_name: mcp4xxx-util-${{ matrix.target }}.tgz
        tag: ${{ github.ref }}
        overwrite: true
